#!/usr/bin/env bash
set -euo pipefail

# This script configures StepMania 5.0 dependencies for Kubuntu 26.04.
# Usage: install_stepmania.sh [STEPMANIA_DIR]
# After running this script, start StepMania with STEPMANIA_DIR/stepmania.sh

# Download StepMania here:
# https://www.stepmania.com/download/

# Songs
# https://search.stepmaniaonline.net/

# This PPA does not work on Ubuntu 24.10,
# as it contains dependencies to old packages.
# https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/stepmania

if [ "${EUID}" -eq 0 ]; then
   echo "This script should not be run as root."
   exit 1
fi
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
STEPMANIA_DIR="$(realpath "${1:-${SCRIPT_DIR}/StepMania-5.0.12-Linux/stepmania-5.0}")"
if [ ! -f "${STEPMANIA_DIR}/stepmania" ]; then
  echo "StepMania executable was not found at: ${STEPMANIA_DIR}/stepmania"
  echo "Give the directory containing the StepMania executable as an argument."
  exit 1
fi

# https://www.reddit.com/r/Stepmania/comments/bkmy8q/stepmania_isnt_opening_on_linux/
# https://www.codeweavers.com/support/forums/general/?t=26;mhl=149152;msg=149152
sudo apt install curl libjpeg62

# StepMania is linked against libpcre.so.3 (PCRE1), which is no longer available in Ubuntu 26.04.
# PCRE2 is not ABI-compatible, so the library is extracted from the Ubuntu 25.10 package
# into a private directory that only StepMania uses, instead of installing it system-wide.
# The checksum is from the GPG-signed Ubuntu 25.10 (questing) universe Packages index.
PCRE_DEB_URL="https://archive.ubuntu.com/ubuntu/pool/universe/p/pcre3/libpcre3_8.39-15.1_amd64.deb"
PCRE_DEB_SHA256="14c8f0a45ab4639d81b3ec6d6d026438005683bf2a7b984fbee9c893b9f61dec"

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT
PCRE_DEB="${TMP_DIR}/libpcre3.deb"
curl --fail --location --proto "=https" --tlsv1.2 --silent --show-error --output "${PCRE_DEB}" "${PCRE_DEB_URL}"
echo "${PCRE_DEB_SHA256}  ${PCRE_DEB}" | sha256sum --check --strict
dpkg-deb --extract "${PCRE_DEB}" "${TMP_DIR}/extracted"

LIB_DIR="${STEPMANIA_DIR}/lib"
mkdir -p "${LIB_DIR}"
install -m 0644 "$(readlink -f "${TMP_DIR}/extracted/lib/x86_64-linux-gnu/libpcre.so.3")" "${LIB_DIR}/libpcre.so.3"

# https://github.com/stepmania/stepmania/issues/2186#issuecomment-1079837345
ln -sfn "/lib/x86_64-linux-gnu/libva.so.2" "${LIB_DIR}/libva.so.1"

LAUNCHER="${STEPMANIA_DIR}/stepmania.sh"
cat > "${LAUNCHER}" << "EOF"
#!/usr/bin/env sh
# Generated by install_stepmania.sh
set -eu
DIR="$(dirname "$(readlink -f "$0")")"
export LD_LIBRARY_PATH="${DIR}/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
cd "${DIR}"
exec "${DIR}/stepmania" "$@"
EOF
chmod 0755 "${LAUNCHER}"

echo "StepMania dependencies installed. Start StepMania with: ${LAUNCHER}"
